/*
 * One step's worth of arguments, for the pattern skeletons in this folder.
 *
 * A family of pattern scripts whose steps differ in four or more values cannot
 * be folded onto one skeleton: `wk` plus four parameters is one over the
 * argument-count threshold. Where the surplus values belong to the *same*
 * engine call, they travel as one of these instead - the same idiom the engine
 * itself uses for Command_Attack_Args and its kin, and the same safety
 * argument as Recipe V, because every value is still written out in full, in
 * the call's own parameter order, at its own call site.
 *
 * Recipe J gave them a second job. A skeleton's step hands one of these to the
 * matching Step_ adapter in com_pattern_run.c, which unpacks it into the call
 * written out in full, so the table carries the same values the switch arm did.
 *
 * Each struct's field order and field types are the parameter order and
 * parameter types of the call it names, taken from com_sub.h.
 * Generated by tools/pattern_table.py.
 */

#ifndef COM_PATTERN_ARGS_H
#define COM_PATTERN_ARGS_H

#include "sf33rd/Source/Game/com/com_sub.h"
#include "types.h"

/* The 2 values Adjust_Attack takes, in its own parameter order. */
typedef struct {
    s16 Reaction;
    u16 Lever_Data;
} Adjust_Attack_Step;

/* The 2 values Approach_Walk takes, in its own parameter order. */
typedef struct {
    s16 Target_Pos;
    s16 Option;
} Approach_Walk_Step;

/* The 2 values Check_EX takes, in its own parameter order. */
typedef struct {
    s16 Next_Action;
    s16 Next_Menu;
} Check_EX_Step;

/* The 2 values Check_SA takes, in its own parameter order. */
typedef struct {
    s16 Next_Action;
    s16 Next_Menu;
} Check_SA_Step;

/* The 2 values Check_SA_Full takes, in its own parameter order. */
typedef struct {
    s16 Next_Action;
    s16 Next_Menu;
} Check_SA_Full_Step;

/* The 3 values Check_Store_Lever takes, in its own parameter order. */
typedef struct {
    u16 Tech_Number;
    s16 Next_Action;
    s16 Next_Menu;
} Check_Store_Lever_Step;

/* The 2 values Com_Random_Select takes, in its own parameter order. */
typedef struct {
    const Branch_Menu_Args* p;
    s16 Rnd_Type;
} Com_Random_Select_Step;

/* The 3 values ETC_Term takes, in its own parameter order. */
typedef struct {
    s16 Exit_No;
    u32 Next_Action;
    u16 Next_Menu;
} ETC_Term_Step;

/* The 1 values Forced_Guard takes, in its own parameter order. */
typedef struct {
    s16 Guard_Type;
} Forced_Guard_Step;

/* The 2 values Hi_Jump takes, in its own parameter order. */
typedef struct {
    s16 Pl_Number;
    s16 Jump_Dir;
} Hi_Jump_Step;

/* The 1 values Jump takes, in its own parameter order. */
typedef struct {
    s16 Time;
} Jump_Step;

/* The 2 values Keep_Away takes, in its own parameter order. */
typedef struct {
    s16 Target_Pos;
    s16 Option;
} Keep_Away_Step;

/* The 2 values Keep_Status takes, in its own parameter order. */
typedef struct {
    u16 Lever_Data;
    s16 Option_Data;
} Keep_Status_Step;

/* The 3 values Lever_Attack takes, in its own parameter order. */
typedef struct {
    s16 Reaction;
    u16 Lever;
    u16 Lever_Data;
} Lever_Attack_Step;

/* The 2 values Lever_On takes, in its own parameter order. */
typedef struct {
    u16 LR_Lever;
    u16 UD_Lever;
} Lever_On_Step;

/* The 1 values Look takes, in its own parameter order. */
typedef struct {
    s16 Time;
} Look_Step;

/* The 2 values Next_Another_Menu takes, in its own parameter order. */
typedef struct {
    s16 Next_Action;
    u16 Next_Menu;
} Next_Another_Menu_Step;

/* The 1 values Next_Be_Flip takes, in its own parameter order. */
typedef struct {
    s16 xx;
} Next_Be_Flip_Step;

/* The 2 values Normal_Attack takes, in its own parameter order. */
typedef struct {
    s16 Reaction;
    u16 Lever_Data;
} Normal_Attack_Step;

/* The 3 values Normal_Attack_SP takes, in its own parameter order. */
typedef struct {
    s16 Reaction;
    u16 Lever_Data;
    s16 Time;
} Normal_Attack_SP_Step;

/* The 1 values Provoke takes, in its own parameter order. */
typedef struct {
    s16 Lever;
} Provoke_Step;

/* The 1 values Push_Shot takes, in its own parameter order. */
typedef struct {
    s16 Power_Level;
} Push_Shot_Step;

/* The 3 values Search_Back_Term takes, in its own parameter order. */
typedef struct {
    s16 Move_Value;
    s16 Next_Action;
    s16 Next_Menu;
} Search_Back_Term_Step;

/* The 1 values Wait takes, in its own parameter order. */
typedef struct {
    s16 Time;
} Wait_Step;

/* The 2 values Wait_Attack_Complete takes, in its own parameter order. */
typedef struct {
    u16 Lever_Data;
    s16 Option;
} Wait_Attack_Complete_Step;

/* The 2 values Wait_Get_Up takes, in its own parameter order. */
typedef struct {
    u16 Lever_Data;
    s16 Option;
} Wait_Get_Up_Step;

/* The 1 values Wait_Lie takes, in its own parameter order. */
typedef struct {
    u16 Lever_Data;
} Wait_Lie_Step;

/* The 3 values Walk takes, in its own parameter order. */
typedef struct {
    u16 Lever;
    s16 Time;
    s16 unused;
} Walk_Step;

/* The calls that take one of the engine's own argument objects. Naming it
 * after the call too lets a step spell it the way every other step is
 * spelled: STEP, the call, and the values, in the call's parameter order. */
typedef Branch_Menu_Args Branch_Unit_Area_Step;
typedef Branch_Wait_Args Branch_Wait_Area_Step;
typedef Command_Attack_Args Command_Attack_Step;
typedef EM_Term_Params EM_Term_Step;
typedef Jump_Attack_Args Hi_Jump_Attack_Step;
typedef Hi_Jump_Term_Args Hi_Jump_Attack_Term_Step;
typedef JCA_Term_Args Hi_Jump_Command_Attack_Term_Step;
typedef Command_Attack_Args J_Command_Attack_Step;
typedef Jump_Attack_Args Jump_Attack_Step;
typedef Jump_Term_Args Jump_Attack_Term_Step;
typedef JCA_Term_Args Jump_Command_Attack_Term_Step;
typedef Lever_Attack_SP_Args Lever_Attack_SP_Step;
typedef ORO_JCA_Term_Args ORO_HJCA_Term_Step;
typedef ORO_Air_Term_Args ORO_JA_Term_Step;
typedef ORO_JCA_Term_Args ORO_JCA_Term_Step;
typedef Rapid_Command_Args Rapid_Command_Attack_Step;
typedef SA_Term_Args SA_Term_Step;
typedef Shell_Term_Params SHELL_Term_Step;
typedef Short_Range_Args Short_Range_Attack_Step;

#endif
