/*
 * One step's worth of arguments, for the pattern skeletons in this folder.
 *
 * A family of pattern scripts whose steps differ in four or more values cannot
 * be folded onto one skeleton: `wk` plus four parameters is one over the
 * argument-count threshold. Where the surplus values belong to the *same*
 * engine call, they travel as one of these instead - the same idiom the engine
 * itself uses for Command_Attack_Args and its kin, and the same safety
 * argument as Recipe V, because every value is still written out in full, in
 * the call's own parameter order, at its own call site.
 *
 * Each struct's field order is the parameter order of the call it names.
 * Generated by tools/passive_fold.py abfold.
 */

#ifndef COM_PATTERN_ARGS_H
#define COM_PATTERN_ARGS_H

#include "types.h"

/* The 2 values Adjust_Attack takes, in its own parameter order. */
typedef struct {
    s16 Reaction;
    u16 Lever_Data;
} Adjust_Attack_Step;

/* The 3 values Check_Store_Lever takes, in its own parameter order. */
typedef struct {
    u16 Tech_Number;
    s16 Next_Action;
    s16 Next_Menu;
} Check_Store_Lever_Step;

/* The 2 values Com_Random_Select takes, in its own parameter order. */
typedef struct {
    const Branch_Menu_Args* p;
    s16 Rnd_Type;
} Com_Random_Select_Step;

/* The 3 values ETC_Term takes, in its own parameter order. */
typedef struct {
    s16 Exit_No;
    u32 Next_Action;
    u16 Next_Menu;
} ETC_Term_Step;

/* The 3 values Lever_Attack takes, in its own parameter order. */
typedef struct {
    s16 Reaction;
    u16 Lever;
    u16 Lever_Data;
} Lever_Attack_Step;

/* The 2 values Normal_Attack takes, in its own parameter order. */
typedef struct {
    s16 Reaction;
    u16 Lever_Data;
} Normal_Attack_Step;

/* The 3 values Search_Back_Term takes, in its own parameter order. */
typedef struct {
    s16 Move_Value;
    s16 Next_Action;
    s16 Next_Menu;
} Search_Back_Term_Step;

#endif
